### ISSUE TITLE
Implement a pet class that can be used by the person class

### ISSUE THREAD

**Issue by nmunro** [nmunro/proj#11]
A pet has a species, a name, has a favorite food, a favorite toy and makes a noise.

This shouldn't extend the person class but be an independent class, maybe put it in its own file (pet.js), a person may have a list of pets and that list should be instances of the pet class.

**Comment by Arditti93** [comment]
the file s in src person.js

**Comment by Arditti93** [comment]
not extended class - researching the correct method

**Comment by Arditti93** [comment]
pets.js merged into master
